name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.2
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Playwright tests
        run: |
          pnpm exec playwright install --with-deps
          pnpm test:e2e  