name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/chipster/**'

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.2
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build Chipster
        run: pnpm run build --filter=@micoblanc/chipster
      
      - name: Test Chipster
        run: pnpm test --filter=@micoblanc/chipster
        
      - name: Publish to npm
        run: cd packages/chipster && pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
